-- Switch to role of ACOUNTADMIN --
USE ROLE ACCOUNTDMIN;
CREATE DATABASE DEMO_DB;
USE DATABASE DEMO_DB;
USE WAREHOUSE COMPUTE_WH;
 
 -- Set up the table --
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.SUPPLIER
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER";


CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.SUPPLIER_CLONE
CLONE DEMO_DB.PUBLIC.SUPPLIER

select * from SUPPLIER_CLONE

UPDATE SUPPLIER_CLONE
SET S_PHONE='#####';

CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.SUPPLIER_CLONE_OF_CLONE
CLONE DEMO_DB.PUBLIC.SUPPLIER_CLONE before (statement => '01b47e08-3201-17e0-0008-e646000141fe')

select * from SUPPLIER_CLONE_OF_CLONE