SELECT * FROM EMPLOYEES_BKP;
SELECT * FROM EMPLOYEES_BKP at (OFFSET => -60*3);

UPDATE EMPLOYEES_BKP set age=19;

DROP TABLE EMPLOYEES;

UNDROP TABLE EMPLOYEES;

CREATE SCHEMA TEST;
UNDROP  SCHEMA TEST;

SHOW TABLES


-------------------------
ALTER TABLE EMPLOYEES_BKP SET DATA_RETENTION_TIME_IN_DAYS=2

